

<form class="form-horizontal" method="post" id="form" onsubmit="return checkForm(this);">
    <div class="control-group">
        <label class="control-label" for="inputName">Naam</label>
        <div class="controls">
            <input type="text" value="<?php echo $this->name;?>" data-required="true" id="inputName" placeholder="Naam" name="name">

        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputTable">Tabel</label>
        <div class="controls">
            <input type="text" value="<?php echo $this->table;?>" data-required="true" id="inputTable" placeholder="Tabelnaam" name="table">

        </div>
    </div>
    <div class="control-group">
        <label class="control-label" for="inputPassword">Definitie</label>
        <div class="controls">
            <textarea rows="20" name="definition" data-required="true" class="input-xxlarge" style="width:600px">
<?php echo $this->definition; ?>
            </textarea>
        </div>
    </div>
    <div class="control-group">
        <div class="controls">

            <button type="submit" class="btn">Update</button>

            <button type="" onclick="removeModule(<?php echo (int) $this->id; ?>);" class="btn btn-danger">Verwijder</button>
        </div>
    </div>
</form>