<form class="form-horizontal" method="post" id="form" onsubmit="return checkForm(this);">

    <?php

    foreach ($this->xml->fields->field as $field) {

        $arr = $field->attributes();
        $name = (string) $arr['name'];

        $value = $this->data[$name];
        switch ($arr['type']) {

            case 'text':
                ?>
    <div class="control-group">
        <label class="control-label" for="inputTable"><?php echo $field->label;?></label>
        <div class="controls">
            <input type="text" value="<?php echo $value;?>" data-required="true" id="inputTable" placeholder="<?php echo $field->label;?>" name="<?php echo $arr['name'];?>">

        </div>
    </div>
        <?
                break;
            case 'textarea':
                ?>
    <div class="control-group">
        <label class="control-label" for="inputTable"><?php echo $field->label;?></label>
        <div class="controls">
            <textarea rows="20" name="<?php echo $arr['name'];?>" data-required="true" class="input-xxlarge"><?php echo $value;?></textarea>
        </div>
    </div>
        <?
                break;
        }

    }

    ?>
    <div class="control-group">
        <div class="controls">

            <button type="submit" class="btn">Update</button>
        </div>
    </div>
</form>