<?php

?>
<div id="content">

    <div id="content-header">
        <h1>Dashboard</h1>
    </div>

    <div id="breadcrumb">
        <a href="#" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a>
        <a href="#" class="current"><?php echo $this->name;?></a>
    </div>
    <div class="container-fluid">
        <!--
        <div class="row-fluid">
            <div class="span12">
                <div class="alert alert-info">
                    Welcome in the <strong>Unicorn Admin Theme</strong>. Don't forget to check all the pages!
                    <a href="#" data-dismiss="alert" class="close">×</a>
                </div>
                <div class="widget-box">
                    <div class="widget-title"><span class="icon"><i class="icon-signal"></i></span><h5>Site Statistics</h5><div class="buttons"><a href="#" class="btn btn-mini"><i class="icon-refresh"></i> Update stats</a></div></div>
                    <div class="widget-content">
                        <div class="row-fluid">
                            <div class="span4">
                                <ul class="site-stats">
                                    <li><i class="icon-user"></i> <strong>1433</strong> <small>Total Users</small></li>
                                    <li><i class="icon-arrow-right"></i> <strong>16</strong> <small>New Users (last week)</small></li>
                                    <li class="divider"></li>
                                    <li><i class="icon-shopping-cart"></i> <strong>259</strong> <small>Total Shop Items</small></li>
                                    <li><i class="icon-tag"></i> <strong>8650</strong> <small>Total Orders</small></li>
                                    <li><i class="icon-repeat"></i> <strong>29</strong> <small>Pending Orders</small></li>
                                </ul>
                            </div>
                            <div class="span8">
                                <div class="chart"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        //-->

        <br >
        <a href="/module/add/<?php echo (int) $this->moduleId;?>" class="btn"><?php echo $this->name;?> toevoegen</a>

        <div class="widget-box">
            <div class="widget-title">
                <span class="icon"><i class="icon-th-list"></i></span>
                <h5>Alle <?php echo $this->name;?></h5>
                <!--
                <span class="label label-info">44</span>
                //-->
            </div>
            <div class="widget-content nopadding">
                <table class="table table-bordered data-table">
                    <thead>
                    <tr>
                        <?php
                            foreach ($this->definition->fields->field as $field) {

                            $arr = $field->attributes();
                            $name = (string) $arr['name'];
                            ?>
                            <th><?php echo $name; ?></th>
                            <?
                            }
                        ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                        foreach ($this->data as $row) {
                        ?>
                        <tr class="gradeX">

                            <?php
                            foreach ($this->definition->fields->field as $field) {

                            $arr = $field->attributes();
                            $name = (string) $arr['name'];
                            ?>
                            <td class="center"><a href="/module/edit/<?php echo $this->moduleId;?>/<?php echo $row['id'];?>"><?php echo $row[$name]; ?></a></td>
                            <?
                            }?>

                        </tr>
                        <?
                        }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>