<?php

?>
<a href="/module/add/<?php echo (int) $this->id;?>" class="btn"><?php echo $this->name;?> toevoegen</a>
<br />
<table class="table table-hover table-bordered table-striped">
<?php
    foreach ($this->data as $row) {
    ?>
    <tr>

        <?php
        foreach ($this->definition->fields->field as $field) {

        $arr = $field->attributes();
        $name = (string) $arr['name'];
        ?>
        <td><a href="/modules/edit/<?php echo $module['id'];?>"><?php echo $row[$name]; ?></a></td>
        <?
        }?>

    </tr>
    <?
    }
?>
</table>