<?php


    foreach ($this->elements as $element)
    {
        $label = $element->getName();
        $type = $element->getType();
        $name = $element->getName();
        $value = $element->getValue();

        switch($type) {
            case 'text':
                ?>
                <div class="control-group">
                    <label class="control-label" for="inputTable"><?php echo $label;?></label>
                    <div class="controls">
                        <input type="text"  data-required="true" id="inputTable" placeholder="<?php echo $label;?>" name="<?php echo $name;?>">

                    </div>
                </div>
                <?
                break;
            case 'textarea':
                ?>
                <div class="control-group">
                    <label class="control-label" for="inputTable"><?php echo $label;?></label>
                    <div class="controls">
                        <textarea rows="20" name="<?php echo $name;?>" data-required="true" class="input-xxlarge"></textarea>
                    </div>
                </div>
        <?
                break;
        }
    }
?>