<form class="form-signin" onsubmit="" action="" method="post">


    <h2 class="form-signin-heading">Thinkfw inloggen</h2>
    <input type="text" name="username" class="input-block-level" placeholder="Gebruikersnaam">
    <input type="password" name="password" class="input-block-level" placeholder="Wachtwoord">
    <label class="checkbox">
        <input type="checkbox" value="remember-me"> Onthoud mij
    </label>
    <button class="btn btn-large btn-primary" type="submit">Login</button>
</form>