<?php

    use Thinkfw\Application;


    if (empty($_SESSION['user'])) {
        Application::redirect('/login');
    }

    $db = Application::getDatabase();
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Thinkfw cms</title>

        <!-- JQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link rel="stylesheet" href="/css/style.css">

        <!-- thinkfw -->

        <script src="/js/thinkfw.js"></script>

        <!-- Bootstrap -->
        <script src="/js/bootstrap.min.js"></script>
        <script type="text/javascript">

            $(function() {
                $('.dropdown-toggle').dropdown();
            });

        </script>

    </head>
    <body>
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </a>

                    <div class="nav-collapse collapse navbar-responsive-collapse">

                        <?php

                            $result = $db->query("SELECT * FROM thinkfw_modules");
                            $resultSet = $db->fetchAll($result);

                            foreach ($resultSet as $module) {
                                ?>
                        <ul class="nav ">
                            <li class="active"><a href="/module/overview/<?php echo (int) $module['id']; ?>"><?php echo $module['name']; ?></a></li>
                        </ul>
                                <?
                            }


                        ?>

                        <?php

                            if ($_SESSION['user']['admin'] === true) :
                            ?>
                        <ul class="nav pull-right">
                            <li class="active"><a href="/modules">Modules</a></li>
                        </ul>
                            <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>


        <?php echo $content; ?>
    </body>
</html>