<?PHP
    if (empty($_SESSION['user'])) {
        \Thinkfw\Application::redirect('/login');
    }
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Thinkfw cms</title>

        <!-- JQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

        <link href="/css/bootstrap.min.css" rel="stylesheet" media="screen">
        <link href="/css/bootstrap-responsive.min.css" rel="stylesheet" media="screen">
        <link rel="stylesheet" href="/css/style.css">
        
        <!-- thinkfw -->

        <script src="/js/thinkfw.js"></script>

        <!-- Bootstrap -->
        <script src="/js/bootstrap.min.js"></script>
        <script type="text/javascript">

            $(function() {
                $('.dropdown-toggle').dropdown();
            });

        </script>

    </head>
    <body>
        <div class="navbar navbar-inverse">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    </a>

                    <div class="nav-collapse collapse navbar-responsive-collapse">
                        <ul class="nav">
                            <li class="active"><a href="#">Home</a></li>
                        </ul>

                        <ul class="nav pull-left">
                            <li><a href="#">Link</a></li>
                            <li class="divider-vertical"></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Projecten <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav pull-right">
                            <li class="active"><a href="/modules">Modules</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>


        <?php echo $content; ?>
    </body>
</html>